### ISSUE TITLE
I think the requirements are for Ubuntu... 

### ISSUE THREAD

**Issue by fusionfoto** [tiagosh/AltcoinGenerator#10]
... or a similar release. This does not execute properly on Raspberry Pi. (Not saying that it should, just suggesting a little more color beyond "docker.io" and "git".

It works like a champ on Ubuntu.

**Comment by tiagosh** [comment]
Thanks for the feedback.
The script should work fine on any linux distribution that has docker and git, not only ubuntu. It runs fine on opensuse as well. The docker instance is self-contained, so it is distribution agnostic.
I will try to improve the warnings so it's more clear what's needed to run the script.

**Comment by fusionfoto** [comment]
I installed docker and git on RPi, there were a lot of complaints that some of the parameter fields weren't being filled out. I think its a very narrow use case and probably not worth any time to "fix"... you've done a great job on Ubuntu from what I've seen.

**Comment by tiagosh** [comment]
Ahh got it! Yes, that's a very specific use case.
If that turns out to be a common scenario in the future we can revisit this issue then.
Thanks for the report!
