### ISSUE TITLE
How to start?

### ISSUE THREAD

**Issue by leegod** [tiagosh/AltcoinGenerator#15]
Hm... there are missing part. 

I am trying to do this at my windows 10 laptop, 

where to start?

I already installed git and docker. 

description says [bash... ]

what is bash? 

where should I start? run CMD and type there? or...? 

Please consider step by step description.

**Comment by ejaz1977pk** [comment]
The script works at Linux (Ubuntu). 

However, you can install VirutalBox at MS Windows to host Ubuntu, log into it, fire up a terminal and there you go.

**Comment by tiagosh** [comment]
Exactly. The script was developed to be used on linux only. It won't work on another operating system.
I indeed forgot to mention that in the README. Although you can run docker, bash and git on windows, the script will likely fail to run.
Better follow @ejaz1977pk 's suggestion and use a linux virtual machine instead.

**Comment by leegod** [comment]
Thanks. I installed virtualbox, but stuck at first. When run it, it says no bootable media found. 

And if I run this Altcoin generator at this virtualbox, always this runs on this virtual ubuntu after I run virtualbox? Now on my windows?

**Comment by tiagosh** [comment]
It won't work on windows. It's linux only. I updated the readme file to properly state that.
You could take the code changed by the script and try building on windows, but that's out of the scope of this script.

**Comment by tiagosh** [comment]
Last week I changed the script to work on a mac as well, but running it on windows is out of the scope of this project.
You could take the code generate on linux and try compiling it on windows manually, but I am not sure the exact steps as I never built litecoin on windows.
