### ISSUE TITLE
Getting Docker response error while execute command

### ISSUE THREAD

**Issue by malvikiran** [tiagosh/AltcoinGenerator#19]
Hello Team,

Can you please check my issue?

root@kiran-mi:~# docker network ls
NETWORK ID          NAME                             DRIVER              SCOPE
e40aa3c0ef39        bridge                           bridge              local
ae4b0d2157f6        composer_default                 bridge              local
5311fa723cfb        dockercompose_default            bridge              local
a241f205b23c        host                             host                local
b866aceef54b        ledger_default                   bridge              local
f50265f9f23b        newcoin                          bridge              local
c9f53d251e55        none                             null                local
397ea0e7b33f        sawtoothhyperdirectory_default   bridge              local

root@kiran-mi:~# docker network inspect newcoin
[
    {
        "Name": "newcoin",
        "Id": "f50265f9f23bc0f3c8b2b58c56112b20e0c17bdece0407666867b5fbaeb4ec28",
        "Created": "2018-02-02T18:15:41.240938155+05:30",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.22.0.0/16",
                    "Gateway": "172.22.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Containers": {},
        "Options": {},
        "Labels": {}
    }
]

******************************************************ISSUE************************************************************************************************************

for i in $(docker ps -q); do docker exec $i /mindcoin/src/mindcoin-cli -regtest generate 2  & done
root@kiran-mi:~# docker: Error response from daemon: User specified IP address is supported only when connecting to networks with user configured subnets.
docker: Error response from daemon: User specified IP address is supported only when connecting to networks with user configured subnets.
ERRO[0005] error getting events from daemon: net/http: request canceled 
docker: Error response from daemon: User specified IP address is supported only when connecting to networks with user configured subnets.
ERRO[0005] error getting events from daemon: net/http: request canceled 
docker: Error response from daemon: User specified IP address is supported only when connecting to networks with user configured subnets.
ERRO[0005] error getting events from daemon: net/http: request canceled 

******************************************************ISSUE************************************************************************************************************

**Comment by tiagosh** [comment]
I would guess you already have another network that overlaps 172.22.0.0/16.
Can you try changing the DOCKER_NETWORK variable in the script to another private network range and check if that makes any difference?

**Comment by tiagosh** [comment]
Nevermind. There was a bug in the script indeed.
It should work fine now. Please give it a try and let me know.

**Comment by tiagosh** [comment]
I will close the issue for now. Please feel free to reopen if it still doesn't work.
Thanks.
