### ISSUE TITLE
nodes won't sync

### ISSUE THREAD

**Issue by ashian** [tiagosh/AltcoinGenerator#20]
I use the script and create a new altcointest, every things goes well and I can generate some blocks. but the problem is nodes will not sync and each of them has their own block count .
What is the problem? I wait a long time without change

**Comment by tiagosh** [comment]
Hi, please take a look at the updated script.
You have to chance the MINIMUM_CHAIN_WORK as instructed in the script to make all nodes sync right away.

**Comment by ashian** [comment]
@tiagosh  Thank you for new changes on script. I will check it about my issue.
But I have a suggestion now, I think it's good idea to add which branch of litecoin want to be cloned.
like this:
LITECOIN_BRANCH=0.14 # in define section    

# clone litecoin
    git clone -b $LITECOIN_BRANCH $LITECOIN_REPOS $COIN_NAME_LOWER

**Comment by tiagosh** [comment]
That's a great idea. Better not to rely on master as the code might change at some point.
Testing as I write and will push the changes soon if everything works as expected.
Thanks.

**Comment by tiagosh** [comment]
Done. Just implemented as you suggested, and added a few more improvements.
Thanks!

**Comment by ashian** [comment]
Great job . Thank you
