### ISSUE TITLE
Assertion `tip' failed

### ISSUE THREAD

**Issue by fvorwerk** [tiagosh/AltcoinGenerator#23]
Everytime I try to use the `bash altcoin_generator.sh start`
i get this message and get no output when I use the echoed commands.

`myoind: validation.cpp:1308: void InvalidChainFound(CBlockIndex*): Assertion `tip' failed.
/bin/bash: line 1:    12 Aborted                 ./src/mycoind -regtest -listen -noconnect -bind=172.18.0.5 -addnode=172.18.0.1 -addnode=172.18.0.2 -addnode=172.18.0.3 -addnode=172.18.0.4`

I'm using an ubuntu server 17.10 64bit setup

**Comment by fvorwerk** [comment]
It was my bad, got some variables in the script wrong.

**Comment by tiagosh** [comment]
Ah, that's ok! Glad it worked!

**Comment by fvorwerk** [comment]
I still can't get the wallet to compile. I have every dependency installed on my Arch Linux machine, still i get 
`Makefile:5413: libbitcoin_server_a-miner.o ] Error 1` and a `[Makefile:8932: all-recursive] Fehler 1` strange even when i run it with the `--disable-wallet` command it won't compile, neither in ubuntu nor in arch.
But keep the great work up! I love the project!
