### ISSUE TITLE
Premining coins

### ISSUE THREAD

**Issue by ejaz1977pk** [tiagosh/AltcoinGenerator#3]
Hi

I used your script to clone Litecoin. Sequel to that, I want to have a certain set of premine coins. For example, in a game of monopoly, the bank (or system) having set of premine coin as well as every player, which they use after rolling dice every time. The system rewards or penalize the player, depending upon the outcome of each dice. Likewise, players may lend money from each other etc.

For this case, could you please advise how can I generate set of premined coins.

Assistance in this matter will be highly appreciated.

**Comment by charlesrocket** [comment]
simple solution could be:

```
int64 static GetBlockValue(int nHeight, int64 nFees)
{
    int64 nSubsidy = 500 * COIN;
    if(nHeight == 3)  
    {
        nSubsidy = 1000000 * COIN;  // premine on 3rd block
    }
    else if(nHeight < 5000)  
    {
        nSubsidy = 5000 * COIN;
    }
    else if(nHeight < 10000)  
    {
        nSubsidy = 2500 * COIN;
    }
```

**Comment by ashian** [comment]
at the moment there is no GetBlockValue function, you may use GetBlockSubsidy in validation.cpp

**Comment by ejaz1977pk** [comment]
Many thanks.

**Comment by tiagosh** [comment]
Hi, thanks everybody.
I updated the script to inject some similar logic in GetBlockSubsidy() as suggested by @charlesrocket and @ashian .
There is a variable PREMINE_AMOUNT that will change the reward of block 1.
Please let me know if that works for you.

**Comment by tiagosh** [comment]
Closing this issue as it seems it's fixed.
