### ISSUE TITLE
Error: networks have overlapping IPv4

### ISSUE THREAD

**Issue by suoko** [tiagosh/AltcoinGenerator#35]
I have this error when running the script for the first time.
What's wrong ?

_Creating docker network
Error response from daemon: cannot create network xxxxxxxxxxxxxxxxxxxxxxxxxxxxx (br-xxxxxxxxxx): conflicts with network yyyyyyyyyyyyyyyyyyyyyyyyyyyyyy (br-yyyyyyyyyyy): networks have overlapping IPv4_

**Comment by tiagosh** [comment]
I remember seeing this message once, and the problem was gone after restarting docker.
Not really sure if that's a bug in the script itself, unless the network specified in the script is indeed overlapping your local network as the message indicates.

**Comment by suoko** [comment]
Hi,

solved by using:
DOCKER_NETWORK="172.15.0"

Thanks anyway!

**Comment by tiagosh** [comment]
Excellent! Thank you!
