### ISSUE TITLE
Can't connect to nodes: Permission Denied - Ubuntu 18.04

### ISSUE THREAD

**Issue by DJTiqer** [tiagosh/AltcoinGenerator#42]
On Ubuntu 18.04, it doesn't work, as it cannot connect to the nodes, because permission is denied. Any ideas? Do I have to run it as root?

**Comment by DJTiqer** [comment]
I have run it again, and the issue appears to originate in Docker not being able to connect to it's own daemon.

**Comment by DJTiqer** [comment]
If it helps, this is what happens if i run the script with the clean_up argument
`Stopping all docker nodes
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.38/containers/json?all=1&filters=%7B%22ancestor%22%3A%7B%22newcoin-env%22%3Atrue%7D%7D: dial unix /var/run/docker.sock: connect: permission denied
Removing all docker nodes
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.38/containers/json?all=1&filters=%7B%22ancestor%22%3A%7B%22newcoin-env%22%3Atrue%7D%7D: dial unix /var/run/docker.sock: connect: permission denied
Removing docker network
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Delete http://%2Fvar%2Frun%2Fdocker.sock/v1.38/networks/newcoin: dial unix /var/run/docker.sock: connect: permission denied`

**Comment by tiagosh** [comment]
You have to make sure your user has permission to talk to the docker daemon. 
The following command should do the trick: sudo usermod -aG docker $(whoami)

**Comment by DJTiqer** [comment]
Do I just copy/paste it into terminal?
Thank you for responding.

**Comment by DJTiqer** [comment]
Issue persists:
Removing all docker nodes
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.38/containers/json?all=1&filters=%7B%22ancestor%22%3A%7B%22newcoin-env%22%3Atrue%7D%7D: dial unix /var/run/docker.sock: connect: permission denied

Example of one of the errors on the clean_up argument

**Comment by DJTiqer** [comment]
The error goes away if I execute `bash altcoin_generator.sh clean_up` as root. Very interesting.

**Comment by DJTiqer** [comment]
Might as well close the issue.
**Closed**

**Comment by tiagosh** [comment]
Yes. It does work as root, but it also works as a regular user if you have your user as part of the docker group. It is recommended to always run the commands as a regular user though.

**Comment by DJTiqer** [comment]
Ah ok. I guess the command just didn't work for me. Thank you for making this amazing project.

**Comment by tiagosh** [comment]
Yes. An er20 token is enough for the most common use cases, and it will be already compatible with most ethereum wallets.

**Comment by DJTiqer** [comment]
Exactly why I have now decided to make one.
