### ISSUE TITLE
Critical bug 0.14

### ISSUE THREAD

**Issue by GerardoTaboada** [tiagosh/AltcoinGenerator#45]
Any clone coin which forked off of Bitcoin core 0.14.x through 0.16.2, is probably affected. This also includes coins that update their code by porting over changes made by Bitcoin Core. 
Here is one of the lines of code in the validation.cpp that needed to be patched. ( https://github.com/bitcoin/bitcoin/commit/d1dee205473140aca34180e5de8b9bbe17c2207d?diff=split#diff-24efdb00bfbe56b140fb006b562cc70bL3035 )
 
Bug code:
Code:
if (!CheckTransaction(*tx, state, false))

Patched code:
Code:
if (!CheckTransaction(*tx, state, true))

You may want to go to a particular wallet's/coin's git to see if it's latest update has the buggy line of code in the validation.cpp. However, some wallet/coin devs tend to change the code slightly, so this check might not be foolproof.

I know for sure that Bitcoin ABC (BCH) and Litecoin implemented the patch. However, I am not certain about the 100's of other altcoins out there. 

Source : https://bitcointalk.org/index.php?topic=5035308.0

**Comment by tiagosh** [comment]
Thanks for the report. Just updated the script to clone litecoin v0.16.
