### ISSUE TITLE
Requires docker

### ISSUE THREAD

**Issue by odomojuli** [tiagosh/AltcoinGenerator#8]
Please list that as dependency

**Comment by tiagosh** [comment]
Hi, what exactly do you mean by dependency?
It is already checking for docker during the startup:
https://github.com/tiagosh/AltcoinGenerator/blob/master/altcoin_generator.sh#L49

And there is a statement in the readme file about it as well.
Thanks!

**Comment by tiagosh** [comment]
Closing as docker is already listed as dependency in the readme file.
